# Generated by Django 2.2.10 on 2021-03-03 03:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=800, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('stock_size', models.PositiveSmallIntegerField(default=10, help_text='enter the quantity to truck out of stock items')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=800, unique=True, verbose_name='sub category')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ecommerce.Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=800)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('image', models.FileField(upload_to='images/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='discount price')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/')),
                ('text', models.CharField(blank=True, max_length=30, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_promational', models.BooleanField(default=False, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.Sub_Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
