# Generated by Django 2.2.10 on 2020-09-20 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 20, 22, 12, 43, 522162, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
