# Generated by Django 2.2.10 on 2020-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200920_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
