# Generated by Django 2.2.10 on 2020-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_sub_category_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
