# Generated by Django 2.2.10 on 2021-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_category_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='images/%Y/%m/%d/', width_field=180),
        ),
    ]
