# Generated by Django 2.2.10 on 2021-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='images/%Y/%m/%d/', width_field=180),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='images/%Y/%m/%d/', width_field=180),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='images/%Y/%m/%d/', width_field=180),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='images/%Y/%m/%d/', width_field=180),
        ),
    ]
