# Generated by Django 2.2.10 on 2021-02-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_product_is_promational'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_promational',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='to_date',
        ),
    ]
