# Generated by Django 2.2.10 on 2021-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20210220_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_promational',
            field=models.BooleanField(default=False),
        ),
    ]
