# Generated by Django 2.2.10 on 2021-02-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=650),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=600, verbose_name='City/Closest Landmark'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=8000),
        ),
    ]
