# Generated by Django 2.2.10 on 2021-03-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210303_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_email',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staff_email',
            name='location',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
